// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtUJDbvAzGO_1TGmWOyZVE4q0hsp1eb5k',
    appId: '1:394576877627:web:eae690b1c95a52eb7e241e',
    messagingSenderId: '394576877627',
    projectId: 'instagram-clone-31031',
    authDomain: 'instagram-clone-31031.firebaseapp.com',
    storageBucket: 'instagram-clone-31031.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdh3p5rp95IXz1S-jipiE8IQY5DZapv3M',
    appId: '1:394576877627:android:c7da564842c74b427e241e',
    messagingSenderId: '394576877627',
    projectId: 'instagram-clone-31031',
    storageBucket: 'instagram-clone-31031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_T1OevXkoUBwKYBHWneVXAbSZT7qrp8',
    appId: '1:394576877627:ios:b9b3a97d40ddcf097e241e',
    messagingSenderId: '394576877627',
    projectId: 'instagram-clone-31031',
    storageBucket: 'instagram-clone-31031.appspot.com',
    iosClientId: '394576877627-ktvt141vs5epdan0pg1ajmd53gb2cabp.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj_T1OevXkoUBwKYBHWneVXAbSZT7qrp8',
    appId: '1:394576877627:ios:b9b3a97d40ddcf097e241e',
    messagingSenderId: '394576877627',
    projectId: 'instagram-clone-31031',
    storageBucket: 'instagram-clone-31031.appspot.com',
    iosClientId: '394576877627-ktvt141vs5epdan0pg1ajmd53gb2cabp.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
